apps/tienda/urls.py
from django.urls import path
from apps.tienda.views import tienda

urlpatterns = [
    path('', tienda, name="Tienda"),

]

carro/urls.py
from django.urls import path
from carro.views import agregar_producto,eliminar_producto,restar_producto,limpiar_carro

app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/", agregar_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/", restar_producto, name="restar"),
    path("limpiar/", limpiar_carro, name="limpiar"),

]

src/urls.py
from django.urls import path
from src.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name="Home"),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

techsolutions/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('servicios/', include('apps.servicios.urls')),

    path('blog/', include('apps.blog.urls')),

    path('contacto/', include('apps.contacto.urls')),

    path('autenticacion/', include('apps.autenticacion.urls')),

    path('tienda/', include('apps.tienda.urls')),

    path('carro/', include('carro.urls')),

    path('', include('src.urls')),

]

apps/tienda/models.py
from django.db.models import *

# Create your models here.

class CategoriaProd(Model):
    nombre = CharField(max_length=50)

    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"

    def __str__(self):
        return self.nombre

class Producto(Model):
    nombre = CharField(max_length=50)
    categorias = ForeignKey(CategoriaProd, on_delete=CASCADE)
    imagen = ImageField(upload_to="tienda", null= True, blank=True)
    precio = FloatField()
    disponibilidad = BooleanField(default=True)
    precio_anterior = FloatField()
    descripcion = CharField(max_length=100)

    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.nombre

apps/tienda/views.py
from django.shortcuts import render
from apps.tienda.models import Producto

# Create your views here.

def tienda(request):

    productos = Producto.objects.all()


    return render(request, "tienda/tienda.html", {"productos": productos})

# ------------------------------------------------------------------------

carro/views.py
from django.shortcuts import render, redirect
from carro.carro import Carro
from apps.tienda.models import Producto

# Create your views here.

def agregar_producto(request, producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.agregar(producto)

    return redirect("Tienda")


def eliminar_producto(request, producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.eliminar(producto)

    return redirect("Tienda")


def restar_producto(request, producto_id):
    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.restar_producto(producto)

    return redirect("Tienda")


def limpiar_carro(request, producto_id):
    carro = Carro(request)

    carro.limpiar_carro()

    return redirect("Tienda")

tienda/templates/carro/widget.html
<table class="table table-bordered" style="color: white;">
    <thead>
    <tr>
        <th colspan="3" class="text-centered">
            Carro compras
        </th>
    </tr>
    <tr>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Suma</th>

    </tr>
    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr>

                    <td> {{value.nombre}} </td>
                    <td> {{value.cantidad}} </td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                        <br/>
                        {{ value.precio }} $RD
                    </td>

                </tr>

            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-centered">
                        Sin productos
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                <p style="color: white;">Total: {{importe_total_carro}} $RD</p>
            </td>
        </tr>
    </tfoot>

</table>